name: Build

on: [ push, pull_request ]


jobs:
  Windows-Build:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Clone CloudCompare
        uses: actions/checkout@v2
        with:
          repository: 'CloudCompare/CloudCompare'
          submodules: true

      - name: Clone Plugin
        uses: actions/checkout@v2
        with:
          path: 'plugins/private/LAS-IO'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: CloudCompareDev
          auto-activate-base: false
          python-version: "3.7"
          miniconda-version: 'latest'

      - name: Install Dependencies
        run: |
          conda install -c conda-forge qt=5.12.* ninja laszip

      - name: Configure MSVC console
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set environment for MSVC
        run: |
          # Set these env vars so cmake picks the correct compiler
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
          echo "CXX=cl.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "CC=cl.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake  `
            -G Ninja `
            -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX=install `
            -DPLUGIN_LAS_IO=ON `
            .

      - name: Build
        run: cmake --build build --parallel

      - name: Install
        run: cmake --install build

  Ubuntu-Build:
    name: "Ubuntu Build"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install build-essential cmake ninja-build libqt5svg5-dev libqt5opengl5-dev qt5-default qttools5-dev qttools5-dev-tools liblaszip-dev

      - name: Clone CloudCompare
        uses: actions/checkout@v2
        with:
          repository: 'CloudCompare/CloudCompare'
          submodules: true

      - name: Clone Plugin
        uses: actions/checkout@v2
        with:
          path: 'plugins/private/LAS-IO'

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake  `
            -G Ninja `
            -B build `
            -DPLUGIN_LAS_IO=ON `
            -DCMAKE_BUILD_TYPE=Release `
            .

      - name: Build
        run: cmake --build build --parallel

      - name: Install
        run: sudo cmake --install build

  MacOs-Build:
    name: "macOs Build"
    runs-on: macos-latest

    steps:
      - name: Clone CloudCompare
        uses: actions/checkout@v2
        with:
          repository: 'CloudCompare/CloudCompare'
          submodules: true

      - name: Clone Plugin
        uses: actions/checkout@v2
        with:
          path: 'plugins/private/LAS-IO'

      - name: Install Dependencies
        run: |
          brew install qt@5 ninja laszip
          python3 -m pip install pytest
          echo "CMAKE_PREFIX_PATH=/usr/local/opt/qt@5" >> $GITHUB_ENV

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake  `
            -G Ninja `
            -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX=install `
            -DPLUGIN_LAS_IO=ON `
            .

      - name: Build
        run: cmake --build build --parallel

      - name: Install
        run: sudo cmake --install build

